grails-app/domain/arm/monitoring/Employee.groovy
package arm.monitoring

class Employee {

    Department department

    String fio

    static constraints = {
        fio maxSize: 255
        fio minSize: 3
    }

    static hasMany = [incidents: Incident]

}

grails-app/domain/arm/monitoring/Issue.groovy
package arm.monitoring

class Issue {

    IssueGroup issueGroup;
    String name;

    int time1 = 1;
    int time2 = 1;
    int time3 = 1;
    int time4 = 1;

    String email1;
    String email2;
    String email3;
    String email4;

    RoadMap roadMap;

    static constraints = {
        email1 nullable: true
        email2 nullable: true
        email3 nullable: true
        email4 nullable: true
        roadMap nullable: true
    }
}

grails-app/controllers/arm/monitoring/EmployeeController.groovy
package arm.monitoring

import grails.transaction.Transactional

import java.text.SimpleDateFormat
import arm.monitoring.Incident

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class EmployeeController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]


    SimpleDateFormat dateFormat = new SimpleDateFormat(IncidentController.SHORT_DATE_PATTERN)

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        def list = Employee.list(params)
        def curDate = new Date();
        def dateString = curDate.format(IncidentController.SHORT_DATE_PATTERN)
        render(view: 'index', model: [employeeList: list, curDate: dateString, employeeCount: Employee.count()])
    }

    def show(Employee employee) {
        respond employee
    }

    def create() {
        respond new Employee(params)
    }

    def incidents() {
        def employee = Employee.findById(params.empID)
        Date date = dateFormat.parse(params.date)
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(date);
        calendar.add(Calendar.DAY_OF_MONTH, 1);
        def tomorrow = calendar.getTime();
//        def list = Incident.findAllByEmployeeAndIssueTimeGreaterThan(employee, date);
        def list = Incident.createCriteria().list {
            and {
                between('issueTime', date, tomorrow)
                eq('employee.id', employee.id)
            }
        }
//        def query = Incident.where {
//            (issueTime < date && issueTime < tomorrow) && this.employee.id == employee.id
//        }
//        def list = criteria.list {};
        render(view: 'incidents', model: [incidents: list, employee: employee, curDay: params.date])
    }

    @Transactional
    def save(Employee employee) {
        if (employee == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (employee.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond employee.errors, view: 'create'
            return
        }

        employee.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'employee.label', default: 'Employee'), employee.id])
                redirect action: 'index'
            }
            '*' { respond employee, [status: CREATED] }
        }
    }

    def edit(Employee employee) {
        respond employee
    }

    @Transactional
    def update(Employee employee) {
        if (employee == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (employee.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond employee.errors, view: 'edit'
            return
        }

        employee.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'employee.label', default: 'Employee'), employee.id])
                redirect action: 'index'
            }
            '*' { respond employee, [status: OK] }
        }
    }

    @Transactional
    def delete(Employee employee) {

        if (employee == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        employee.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'employee.label', default: 'Employee'), employee.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'employee.label', default: 'Employee'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/employee/create.gsp
<%@ page import="arm.monitoring.Department" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'employee.label', default: 'Employee')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-employee" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                 default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-employee" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.employee}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.employee}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form resource="${this.employee}" method="POST">
        <fieldset class="form col-sm-6" style="background-color: #ebffa7">

            <my:select name="department.id" label="Цех"
                       from="${arm.monitoring.Department.list()}"
                       optionKey="id"
                       optionValue="name"/>

            <my:field bean="${employee}" prop="fio" label="ФИО"/>
            <button type="submit" class="btn btn-primary pull-right">Сохранить</button>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/employee/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'employee.label', default: 'Employee')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-employee" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                               default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-employee" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.employee}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.employee}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form resource="${this.employee}" method="POST">
        <fieldset class="form col-sm-6" style="background-color: #ebffa7">

            <my:select name="department.id" label="Цех"
                       from="${arm.monitoring.Department.list()}"
                       optionKey="id"
                       optionValue="name"/>

            <my:field bean="${employee}" prop="fio" label="ФИО"/>
            <button type="submit" class="btn btn-primary pull-right">Сохранить</button>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/employee/incidents.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'employee.label', default: 'Employee')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div class="nav" role="navigation">
    <ul style="margin-top: 5px">
        <li><g:link class="create" controller="incident" action="create"
                    params="[empId: employee.id]">Новый инцидент</g:link></li>

        <li class="form-inline">
            <div class="form-group ">
                <label for="datepicker">Фильтр по дню</label>
                <input type="text" class="form-control" id="datepicker"
                       value="${curDay}"
                       data-provide="datepicker-inline"
                       data-date-format="mm.dd.yyyy">
                <button id="datepicker-ok-btn" class="btn btn-warning">Применить</button>
            </div>
        </li>
    </ul>

    <div class="content scaffold-list" role="main">
        <table class="table table-bordered">
            <thead>
            <th>Цех</th>
            <th>ФИО <br/> работника</th>
            <th>Выявленная проблема</th>
            <th>Заметка</th>
            <th>Дата <br/> нарушения</th>
            <th>Время <br/> выявления</th>
            <th>Состояние</th>
            <th>Время <br/> эскалации <br/> на тек. уровень</th>
            <th>Время <br/> на решение <br/> (час)</th>
            <th>Текущий <br/> уровень</th>
            <th>Создатель</th>
            </thead>
            <tbody>
            <g:each in="${incidents}" var="inc">
                <tr>
                    <td>${inc.employee.department.name}</td>
                    <td>${inc.employee.fio}</td>
                    <td>${inc.issue.name}</td>
                    <td>${inc.descr}</td>
                    <td><g:formatDate format="yyyy-MM-dd" date="${inc.issueTime}"/></td>
                    <td><g:formatDate format="yyyy-MM-dd" date="${inc.detectTime}"/></td>
                    <g:if test="${inc.solved}">
                        <td class="success">Решено</td>
                    </g:if>
                    <g:else>
                        <td class="danger">не решено</td>
                    </g:else>
                    <td>
                        <g:if test="${inc.escalation != null}">
                            <g:formatDate format="yyyy-MM-dd HH:mm" date="${inc.escalation?.dateTime}"/>
                        </g:if>
                        <g:else>
                            Нет
                        </g:else>
                    </td>
                    <td>${inc.getSolvingTime()}</td>
                    <td>${inc.getEscalation()?.getLevel()?.getLabel()}</td>
                    <td>${inc.createdBy.fio}</td>
                </tr>
            </g:each>
            </tbody>
        </table>
    </div>
</div>
</body>

grails-app/views/employee/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'employee.label', default: 'Employee')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-employee" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                               default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><g:link class="create" action="create">Cоздать нового сотрудника</g:link></li>
        <li class="pull-right">
            <div class="pagination pagination-custom">
                <g:paginate total="${issueCount ?: 0}"/>
            </div>
        </li>
    </ul>
</div>

<div id="list-employee" class="content scaffold-list" role="main">
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table class="table table-bordered table-hover">
        <thead>
        <th>ФИО</th>
        <th>Цех</th>
        <th colspan="3">Действия</th>
        </thead>
        <tbody>

        <g:each in="${employeeList}" var="emp">
            <tr>
                <td>${emp.fio}</td>
                <td>${emp.department.name}</td>
                <td>
                    <g:link action="incidents" params="[empID: emp.id, date: curDate]">
                        <span title="Посмотреть инциденты" class="glyphicon glyphicon-exclamation-sign"></span>
                    </g:link>
                </td>
                <td><g:link action="edit" id="${emp.id}">
                    <span title="Изменить" class="glyphicon glyphicon-edit"></span></g:link>
                </td>
                <td>
                    <a href="#" data-toggle=confirmation
                       data-href="${request.contextPath}/department/delete/${emp.id}">
                        <span title="Удалить" class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
        </g:each>

        </tbody>
    </table>
</div>
</body>
</html>

grails-app/views/employee/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'employee.label', default: 'Employee')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-employee" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-employee" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="employee" />
            <g:form resource="${this.employee}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.employee}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>