grails-app/domain/arm/monitoring/Department.groovy
package arm.monitoring
/**
 * Цех
 */
class Department {

    String name;

    DepartmentGroup group;

    static constraints = {
        name maxSize: 255
        name minSize: 1
    }
}

grails-app/controllers/arm/monitoring/DepartmentController.groovy
package arm.monitoring

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class DepartmentController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Department.list(params), model: [departmentCount: Department.count()]
    }

    def show(Department department) {
        respond department
    }

    def create() {
        respond new Department(params)
    }

    @Transactional
    def save(Department department) {
        if (department == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (department.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond department.errors, view: 'create'
            return
        }

        department.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'department.label', default: 'Department'), department.name])
                redirect action: 'index'
            }
            '*' { respond department, [status: CREATED] }
        }
    }

    def edit(Department department) {
        respond department
    }

    @Transactional
    def update(Department department) {
        if (department == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (department.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond department.errors, view: 'edit'
            return
        }

        department.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'department.label', default: 'Department'), department.id])
                redirect action: "index"
            }
            '*' { respond department, [status: OK] }
        }
    }

    @Transactional
    def delete(Department department) {

        if (department == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        department.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'department.label', default: 'Department'), department.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'department.label', default: 'Department'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/department/create.gsp
<%@ page import="arm.monitoring.DepartmentGroup" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'department.label', default: 'Department')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<div id="create-department" class="content scaffold-create" role="main">

    <h1><g:message code="default.create.label" args="${['Цех']}"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.department}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.department}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form resource="${this.department}" method="POST">
        <fieldset class="form col-sm-6" style="background-color: #ebffa7">

            <my:select name="group.id" label="Группа"
                       from="${DepartmentGroup.list()}"
                       optionKey="id"
                       optionValue="name"/>

            <my:field bean="${department}" prop="name" label="Название цеха"/>
            <button type="submit" class="btn btn-primary pull-right">Сохранить</button>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/department/edit.gsp
<%@ page import="arm.monitoring.DepartmentGroup" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'department.label', default: 'Department')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-department" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-department" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="ЦЕХ" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.department}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.department}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.department}" method="PUT">
                <g:hiddenField name="version" value="${this.department?.version}" />
                <fieldset class="form col-sm-6" style="background-color: #ebffa7">

                    <my:select name="group.id" label="Группа"
                               from="${arm.monitoring.DepartmentGroup.list()}"
                               optionKey="id"
                               optionValue="name"/>

                    <my:field bean="${department}" prop="name" label="Название цеха"/>
                    <button type="submit" class="btn btn-primary pull-right">Сохранить</button>
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/department/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'department.label', default: 'Department')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>

<g:render template="/shared/mainMenu"></g:render>

<div class="nav" role="navigation">
    <ul>
        <li><g:link class="create" action="create">Добавить цех</g:link></li>
        <li class="pull-right">
            <div class="pagination">
                <g:paginate total="${departmentCount ?: 0}"/>
            </div>
        </li>
    </ul>
</div>

<div id="list-department" class="content scaffold-list" role="main">
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <div class="alert-popup" role="alert"></div>
    <table class="table table-bordered table-hover">
        <thead>
        <th>№</th>
        <th>Группа</th>
        <th>Название</th>
        <th colspan="2">Действия</th>
        </thead>
        <tbody>

        <g:each in="${departmentList}" var="dep">
            <tr>
                <td>${dep.id}</td>
                <td>${dep.group?.name}</td>
                <td>${dep.name}</td>
                <td><g:link action="edit" id="${dep.id}"><span title="Изменить"
                                                               class="glyphicon glyphicon-edit"></span></g:link>
                </td>
                <td>
                    <a href="#" data-toggle=confirmation
                       data-href="${request.contextPath}/department/delete/${dep.id}">
                        <span title="Удалить" class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
        </g:each>

        </tbody>
    </table>
</div>
</body>
</html>

grails-app/views/department/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'department.label', default: 'Department')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-department" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-department" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="department" />
            <g:form resource="${this.department}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.department}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>