grails-app/domain/arm/monitoring/Issue.groovy
package arm.monitoring

class Issue {

    IssueGroup issueGroup;
    String name;

    int time1 = 1;
    int time2 = 1;
    int time3 = 1;
    int time4 = 1;

    String email1;
    String email2;
    String email3;
    String email4;

    RoadMap roadMap;

    static constraints = {
        email1 nullable: true
        email2 nullable: true
        email3 nullable: true
        email4 nullable: true
        roadMap nullable: true
    }
}

grails-app/controllers/arm/monitoring/IssueController.groovy
package arm.monitoring

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class IssueController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 20, 100)
        respond Issue.list(params), model: [issueCount: Issue.count()]
    }

    def show(Issue issue) {
        respond issue
    }

    def list() {
        def group = IssueGroup.findById(params.group);
        def list = Issue.findAllByIssueGroup(group);
        respond list, formats: ['json']
    }

    def create() {
        respond new Issue(params)
    }

    @Transactional
    def save(Issue issue) {
        if (issue == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (issue.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond issue.errors, view: 'create'
            return
        }

        issue.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'issue.label', default: 'Issue'), issue.id])
                redirect issue
            }
            '*' { respond issue, [status: CREATED] }
        }
    }

    def edit(Issue issue) {
        respond issue
    }

    @Transactional
    def update(Issue issue) {
        if (issue == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (issue.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond issue.errors, view: 'edit'
            return
        }

        issue.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'issue.label', default: 'Issue'), issue.id])
                redirect issue
            }
            '*' { respond issue, [status: OK] }
        }
    }

    @Transactional
    def delete(Issue issue) {

        if (issue == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        issue.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'issue.label', default: 'Issue'), issue.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'issue.label', default: 'Issue'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/issue/create.gsp
<%@ page import="arm.monitoring.IssueGroup" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'issue.label', default: 'Issue')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<div id="create-issue" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="['Замечания']"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.issue}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.issue}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form resource="${this.issue}" method="POST">

        <fieldset class="form col-sm-6 create-f" style="background-color: #ebffa7">
            <fieldset class="fieldset">
                <legend>Группа и наименование</legend>
                <my:select value="${issue?.issueGroup?.id}" class="form-control"
                           name="issueGroup.id" from="${IssueGroup.list()}" optionKey="id" optionValue="name"/>
                <my:field bean="${issue}" prop="name" placeholder="Наименование"/>
            </fieldset>

            <div class="form-group">
                <fieldset class="fieldset">
                    <legend>1й уровень эскалации</legend><br/>
                    <my:field bean="${issue}" prop="email1" label="Email адреса"/>
                    <my:field bean="${issue}" placeholder="24"
                              prop="time1"
                              label="Время эскалации на след. уровень (часов):"/>
                </fieldset>
            </div>

            <div class="form-group">
                <fieldset class="fieldset">
                    <legend>2й уровень эскалации</legend><br/>
                    <my:field bean="${issue}" prop="email2" label="Email адреса"/>
                    <my:field bean="${issue}" placeholder="24"
                              prop="time2"
                              label="Время эскалации на след. уровень (часов):"/>
                </fieldset>
            </div>

            <div class="form-group">
                <fieldset class="fieldset">
                    <legend>3й уровень эскалации</legend><br/>
                    <my:field bean="${issue}" prop="email3" label="Email адреса"/>
                    <my:field bean="${issue}" placeholder="24"
                              prop="time3"
                              label="Время эскалации на след. уровень (часов):"/>
                </fieldset>
            </div>

            <div class="form-group">
                <fieldset class="fieldset">
                    <legend>4й уровень эскалации</legend><br/>
                    <my:field bean="${issue}" prop="email4" label="Email адреса"/>
                    <my:field bean="${issue}" placeholder="24"
                              prop="time4"
                              label="Время эскалации на след. уровень (часов):"/>
                </fieldset>
            </div>
            <button type="submit" class="btn btn-primary pull-right">Сохранить</button>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/issue/edit.gsp
<%@ page import="arm.monitoring.IssueGroup" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'issue.label', default: 'Issue')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-issue" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                            default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-issue" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="['Замечания']"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.issue}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.issue}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form resource="${this.issue}" method="PUT">
        <g:hiddenField name="version" value="${this.issue?.version}"/>
        <fieldset class="form col-sm-6 create-f" style="background-color: #ebffa7">
            <fieldset class="fieldset">
                <legend>Группа и наименование</legend>

                <my:select name="issueGroup.id" value="${issue?.issueGroup?.id}" class="form-control"
                           from="${arm.monitoring.IssueGroup.list()}" optionKey="id"
                           optionValue="name"/>
                <my:field bean="${issue}" prop="name"/>
            </fieldset>

            <div class="form-group">
                <fieldset class="fieldset">
                    <legend>1й уровень эскалации</legend><br/>
                    <my:field bean="${issue}" prop="email1" label="Email адреса"/>
                    <my:field bean="${issue}" placeholder="24"
                              prop="time1"
                              label="Время эскалации на след. уровень (часов):"/>
                </fieldset>
            </div>

            <div class="form-group">
                <fieldset class="fieldset">
                    <legend>2й уровень эскалации</legend><br/>
                    <my:field bean="${issue}" prop="email2" label="Email адреса"/>
                    <my:field bean="${issue}" placeholder="24"
                              prop="time2"
                              label="Время эскалации на след. уровень (часов):"/>
                </fieldset>
            </div>

            <div class="form-group">
                <fieldset class="fieldset">
                    <legend>3й уровень эскалации</legend><br/>
                    <my:field bean="${issue}" prop="email3" label="Email адреса"/>
                    <my:field bean="${issue}" placeholder="24"
                              prop="time3"
                              label="Время эскалации на след. уровень (часов):"/>
                </fieldset>
            </div>

            <div class="form-group">
                <fieldset class="fieldset">
                    <legend>4й уровень эскалации</legend><br/>
                    <my:field bean="${issue}" prop="email4" label="Email адреса"/>
                    <my:field bean="${issue}" placeholder="24"
                              prop="time4"
                              label="Время эскалации на след. уровень (часов):"/>
                </fieldset>
            </div>
            <button type="submit" class="btn btn-primary pull-right">Сохранить</button>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/issue/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'issue.label', default: 'Issue')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-issue" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                            default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><g:link class="create" action="create">Создать новое замечание</g:link></li>

        <li class="pull-right">
            <div class="pagination pagination-custom">
                <g:paginate total="${issueCount ?: 0}"/>
            </div>
        </li>
    </ul>
</div>

<div id="list-issue" class="content scaffold-list" role="main">

    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <div class="alert-popup" role="alert"></div>
    <table class="table table-bordered table-hover" title="Справочник замечаний">
        <colgroup>
            <col style="width: 1%">
            <col style="width: 10%">
            <col style="width: 15%">
        </colgroup>
        <thead>
        <tr>
            <th rowspan="2">№</th>
            <th rowspan="2">Группа</th>
            <th rowspan="2">Название</th>
            <th colspan="2">1й уровень</th>
            <th colspan="2">2й уровень</th>
            <th colspan="2">3й уровень</th>
            <th colspan="2">4й уровень</th>
            <th colspan="3">Название проекта, ДК</th>
            <th rowspan="2">Действия</th>
        </tr>
        <tr>
            <th>email</th>
            <th>время</th>
            <th>email</th>
            <th>время</th>
            <th>email</th>
            <th>время</th>
            <th>email</th>
            <th>время</th>
            <th>Наименование</th>
            <th>Дата начала</th>
            <th>Дата окончания</th>
        </tr>
        </thead>
        <tbody>

        <g:each in="${issueList}" var="i">
            <tr>
                <td>${i.id}</td>
                <td>${i.issueGroup.name}</td>
                <td>${i.name}</td>
                <td>${i.email1?.replace(";", ", ")}</td>
                <td>${i.time1}</td>
                <td>${i.email2?.replace(";", ", ")}</td>
                <td>${i.time2}</td>
                <td>${i.email3?.replace(";", ", ")}</td>
                <td>${i.time3}</td>
                <td>${i.email4?.replace(";", ", ")}</td>
                <td>${i.time4}</td>
                <td>${i.roadMap?.name}</td>
                <td>${i.roadMap?.startDate}</td>
                <td>${i.roadMap?.endDate}</td>

                <td class="actions-cell"><g:link action="edit" id="${i.id}">
                    <span title="Изменить"
                          class="glyphicon glyphicon-edit"></span></g:link>

                    <a href="${request.contextPath}/roadMap/create?issue=${i.id}" title="Добавить дорожную карту"
                        <span class="glyphicon glyphicon-tasks"></span>
                    </a>

                    <a href="#" data-toggle=confirmation
                       data-href="${request.contextPath}/department/delete/${i.id}">
                        <span title="Удалить" class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
        </g:each>
        </tbody>
    </table>

</div>
</body>
</html>

grails-app/views/issue/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'issue.label', default: 'Issue')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-issue" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-issue" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="issue" />
            <g:form resource="${this.issue}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.issue}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>